services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    env_file:
      - ./backend/.env       # <-- Use this to load env variables from your .env file inside backend
    depends_on:
      - mongodb

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
